import {
  Activity,
  Apple,
  Award,
  Baby,
  BarChart3,
  Brain,
  CalendarCheck,
  ClipboardList,
  Droplet,
  Dumbbell,
  Egg,
  Flame,
  FlaskConical,
  GraduationCap,
  Heart,
  HeartPulse,
  Leaf,
  LineChart,
  MessageCircle,
  Moon,
  NotebookPen,
  PartyPopper,
  PlayCircle,
  Salad,
  Scale,
  ShieldCheck,
  ShieldPlus,
  Smartphone,
  Sparkles,
  Stethoscope,
  Sun,
  Target,
  TrendingUp,
  Users,
  Utensils,
  Video,
  Wheat,
  Wind,
  type LucideIcon,
} from 'lucide-react';

import type { IconName } from '@/types';

const registry: Record<IconName, LucideIcon> = {
  activity: Activity,
  apple: Apple,
  award: Award,
  baby: Baby,
  'bar-chart': BarChart3,
  brain: Brain,
  'calendar-check': CalendarCheck,
  'clipboard-list': ClipboardList,
  droplet: Droplet,
  dumbbell: Dumbbell,
  egg: Egg,
  flame: Flame,
  'flask-conical': FlaskConical,
  'graduation-cap': GraduationCap,
  heart: Heart,
  'heart-pulse': HeartPulse,
  leaf: Leaf,
  'line-chart': LineChart,
  'message-circle': MessageCircle,
  moon: Moon,
  'notebook-pen': NotebookPen,
  'party-popper': PartyPopper,
  'play-circle': PlayCircle,
  salad: Salad,
  scale: Scale,
  'shield-check': ShieldCheck,
  'shield-plus': ShieldPlus,
  smartphone: Smartphone,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  sun: Sun,
  target: Target,
  'trending-up': TrendingUp,
  users: Users,
  utensils: Utensils,
  video: Video,
  wheat: Wheat,
  wind: Wind,
};

export function getIcon(name: IconName): LucideIcon {
  return registry[name];
}
